name: Utils deployment

on:
  push:
    branches:
      - main
    paths:
      - 'tools/utils'

jobs:
  publish:
    name: Publish Utils
    runs-on: ubuntu-latest

    steps:
      - run: echo 'Utils Published'
